version: "3.3"

services:
  master:
    image: joellefkowitz/pipeline_master:0.1.0_dev
    ports:
      - 8010:8010
    volumes:
      - ./tokens/master:/tokens/master
    depends_on:
      - postgres
      - vault

  worker:
    image: joellefkowitz/pipeline_worker:0.1.0_dev
    volumes:
      - ./tokens/worker:/tokens/worker
    depends_on:
      - vault

  vault:
    image: joellefkowitz/pipeline_vault:0.1.0_dev
    volumes:
      - ./tokens/worker:/tokens/worker
      - ./tokens/master:/tokens/master
      - ./tokens/postgres:/tokens/postgres

  postgres:
    image: joellefkowitz/pipeline_postgres:0.1.0_dev
    user: postgres
    volumes:
      - ./tokens/postgres:/tokens/postgres
    depends_on:
      - vault
