version: "3.3"

services:
  master:
    image: joellefkowitz/pipeline_master:0.1.0_dev
    ports:
      - 8010:8010
    volumes:
      - /tokens/master.json
    depends_on:
      - postgres
      - vault

  worker:
    image: joellefkowitz/pipeline_worker:0.1.0_dev
    volumes:
      - /tokens/worker.json
    depends_on:
      - vault

  vault:
    image: joellefkowitz/pipeline_vault:0.1.0_dev
    volumes:
      - /tokens/worker.json
      - /tokens/master.json
      - /tokens/postgres.json

  postgres:
    image: joellefkowitz/pipeline_postgres:0.1.0_dev
    user: postgres
    volumes:
      - /tokens/postgres.json
    depends_on:
      - vault
